apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-es
  namespace: kube-monitoring
  labels:
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-es
  labels:
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  - "secrets"
  - "pods/log"
  - "deployments"
  - "batch"
  - "extensions"
  - "crontabs"
  verbs:
  - "get"
  - "watch"
  - "list"
  - "update"
  - "post"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-es
  labels:
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: fluentd-es
  namespace: kube-monitoring
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluentd-es
  apiGroup: ""
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-es-v2.0.4
  namespace: kube-monitoring
  labels:
    k8s-app: fluentd-es
    version: v2.0.4
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-es
      version: v2.0.4
  template:
    metadata:
      labels:
        k8s-app: fluentd-es
        kubernetes.io/cluster-service: "true"
        version: v2.0.4
      # This annotation ensures that fluentd does not get evicted if the node
      # supports critical pod annotation based priority scheme.
      # Note that this does not guarantee admission on the nodes (#40573).
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      hostNetwork: true
      priorityClassName: system-node-critical
      serviceAccountName: fluentd-es
      containers:
      - name: fluentd-es
        image: alogoc/fluentd-elasticsearch:v2.0.4-ui
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2048Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
           privileged: true
        volumeMounts:
         - name: varlog
           mountPath: /var/log
         - name: varlibdockercontainers
           mountPath: /var/lib/docker/containers
           readOnly: true
         - name: config-volume
           mountPath: /etc/fluent/config.d
         - name: docker-sock
           mountPath: /var/run/docker.sock
         - name: libsystemd
           mountPath: /usr/lib64/libsystemd.so.0
         - name: varrun
           mountPath: /var/run
        ports:
         - containerPort: 24224
           name: in-forward
           protocol: TCP
         - containerPort: 9880
           name: http
           protocol: TCP
         - containerPort: 161
           name: snmp
           protocol: UDP
         - containerPort: 5160
           name: in-udp
           protocol: UDP
         - containerPort: 5170
           name: in-tcp
           protocol: TCP
         - containerPort: 5140
           name: in-syslog
           protocol: TCP
         - containerPort: 9292
           name: fluentd-ui
           protocol: TCP
         - containerPort: 24231
           name: promths-mtr
           protocol: TCP
         - containerPort: 24220
           name: monitor-agnt
           protocol: TCP
      nodeSelector:
        beta.kubernetes.io/fluentd-ds-ready: "true"
      terminationGracePeriodSeconds: 30
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: varrun
        hostPath:
          path: /var/run
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: libsystemd
        hostPath:
          path: /usr/lib64/libsystemd.so.0
      - name: config-volume
        configMap:
          name: fluentd-es-config-v0.1.4
